# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: process.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprocess.proto"\x1f\n\x0eProcessRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x01\n\x04type\x18\x02 \x01(\t"\x15\n\tProcessID\x12\n\n\x02id\x18\x01 \x01(\t"1\n\x0cProcessState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t"&\n\rResumeRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c"<\n\x0fProcessResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t"N\n\x0eStatusResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05"\x07\n\x05\x45mpty"J\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bserver_name\x18\x02 \x01(\t\x12\x15\n\rprocess_count\x18\x03 \x01(\x05\x32\xd4\x01\n\x0eProcessManager\x12\x36\n\x0cStartProcess\x12\x0f.ProcessRequest\x1a\x10.ProcessResponse"\x03\x90\x02\x01\x12\x30\n\x0cPauseProcess\x12\n.ProcessID\x1a\r.ProcessState"\x05\x90\x02\x01\x12\x37\n\rResumeProcess\x12\x0e.ResumeRequest\x1a\x10.ProcessResponse"\x04\x90\x02\x01\x12\x2f\n\tGetStatus\x12\n.ProcessID\x1a\x0f.StatusResponse"\x05\x90\x02\x01\x12\x2e\n\x0bHealthCheck\x12\x06.Empty\x1a\x0f.HealthResponse"\x06\x90\x02\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'process_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROCESSREQUEST']._serialized_start=17
  _globals['_PROCESSREQUEST']._serialized_end=48
  _globals['_PROCESSID']._serialized_start=50
  _globals['_PROCESSID']._serialized_end=71
  _globals['_PROCESSSTATE']._serialized_start=73
  _globals['_PROCESSSTATE']._serialized_end=122
  _globals['_RESUMEREQUEST']._serialized_start=124
  _globals['_RESUMEREQUEST']._serialized_end=162
  _globals['_PROCESSRESPONSE']._serialized_start=164
  _globals['_PROCESSRESPONSE']._serialized_end=224
  _globals['_STATUSRESPONSE']._serialized_start=226
  _globals['_STATUSRESPONSE']._serialized_end=304
  _globals['_EMPTY']._serialized_start=306
  _globals['_EMPTY']._serialized_end=313
  _globals['_HEALTHRESPONSE']._serialized_start=315
  _globals['_HEALTHRESPONSE']._serialized_end=389
  _globals['_PROCESSMANAGER']._serialized_start=392
  _globals['_PROCESSMANAGER']._serialized_end=604
# @@protoc_insertion_point(module_scope)
